### ISSUE TITLE
"failsafe" parameter not working for check_credentials

### ISSUE THREAD

**Issue by nabinkhadka** [openzim/python-storagelib#1]
For case with **incorrect**  creds in the URL, I can see the following

```
>>> from kiwixstorage import KiwixStorage
>>> s3_storage = KiwixStorage('https://s3.eu-central-1.wasabisys.com/?keyId=XXXXX&secretAccessKey=XXXXXX&bucketName=testbucket-nabin')
>>>s3_storage.check_credentials(list_buckets=True, failsafe=True)
False
```
In this case, the failsafe command works as expected.

Now , if I check for access to the bucket in URL,
```
>>> s3_storage.check_credentials(bucket=True, failsafe=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nabin/upwork/kiwix/v3.8/lib/python3.8/site-packages/kiwixstorage/__init__.py", line 331, in check_credentials
    self.test_access_bucket(bucket_name=bucket_name)
  File "/Users/nabin/upwork/kiwix/v3.8/lib/python3.8/site-packages/kiwixstorage/__init__.py", line 277, in test_access_bucket
    if self.get_bucket(bucket_name).creation_date is None:
  File "/Users/nabin/upwork/kiwix/v3.8/lib/python3.8/site-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/Users/nabin/upwork/kiwix/v3.8/lib/python3.8/site-packages/boto3/s3/inject.py", line 72, in bucket_load
    response = self.meta.client.list_buckets()
  File "/Users/nabin/upwork/kiwix/v3.8/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/nabin/upwork/kiwix/v3.8/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListBuckets operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

The `failsafe` parameter does not work as expected. Similar behavior can be seen for other checks as well.

**Comment by nabinkhadka** [comment]
While working at feedback on [this](https://github.com/openzim/youtube/pull/79), I wanted to be sure if the creds can read and write a bucket. So I now need to add another try-except for achieving that which would have been good if `failsafe` helped.

**Comment by rgaudin** [comment]
you can check this with `write=True, read=True`.

I’ve identified other cases where it raises instead of returning False that are similar but different to the one you reported.
Will fix and inform you.
If your credentials are Ok, it won’t fail though.

**Comment by nabinkhadka** [comment]
@rgaudin Throws exception with write=True and read=True

**Comment by rgaudin** [comment]
That's exactly what I said. there are uncaught cases at the moment. But, it means your credentials are not OK.

I just pushed a script that simplifies testing. You can use it like:

``` sh
PYTHONPATH=$(pwd)/src/ python src/kiwixstorage/test_credentials.py "https://xxxxx"
```

I see in your URL above that you use the `eu-central-1` region in your URL. If the bucket you created is on another region (you had to choose where to create it and you can see it in your buckets list), then it won't work. That may be your problem.
