### ISSUE TITLE
`check_credentials(write=True)` fails when credential only has the write permission.

### ISSUE THREAD

**Issue by FledgeXu** [openzim/python-storagelib#11]
As I mentioned earlier, When credential only has the write permission, the `check_credentials(write=True)` will fail.

Repeat code:
```python
from kiwixstorage import KiwixStorage
# This key only has write permission
a = KiwixStorage("YOUR KEY")
a.check_credentials(write=True)
```
The reasons is we accidentally call the `delete_obejct` in `test_access_write`
https://github.com/openzim/python-storagelib/blob/ddf166224072986f534ff974186217389966532b/src/kiwixstorage/__init__.py#L307-L308

**Comment by rgaudin** [comment]
Thanks

**Comment by rgaudin** [comment]
check_credentials will also raise exceptions on malformed URL. This should be captured and logged.
