### ISSUE TITLE
Moving/renaming this repo/project

### ISSUE THREAD

**Issue by kelson42** [openzim/python-storagelib#7]
I believe this repo would benefit of a move to:
* github org openzim
* A gnereic name (in pypi)

**Comment by rgaudin** [comment]
Agrees with move to openzim. I don't understand the second question. Current python module (so Pypi) is `kiwixstorage`

**Comment by kelson42** [comment]
Not 100% satified to have `kiwixstorage` handled in `openzim` github organisation. Would something like `easy-s3-storage` a better name, or maybe you have a better name in mind for Pypi?

**Comment by rgaudin** [comment]
Well it's not possible to *rename* a package on PyPI so it would mean either duplicate it or delete and re-upload using a different name. Deleting would mean breaking all scrapers and tools that use it obviously. Changing would also require changing the dependencies everywhere.

While I understand the name is not totally adequate, I think it's not worth the trouble.
